# configs/server/config.yaml
provider_controller:
  providers:
      - id:   "ollama"
        type: "ollama"
        host: "localhost"
        port: 11434
        models:
        - "gemma3"

task_controller:
  policy:
    task_wrapper: "default"
    task_divider: "default"
    task_board:   "default"

http:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

transport:
  type: "libp2p"
  libp2p:
    addrs:
      - "/ip4/0.0.0.0/tcp/0"